version: '3'

services:
  runtrains-server:
    image: runtrains-server
    environment:
      JMRI_HOST: "${JMRI_HOST}"
      CBUS_HOST: "${CBUS_HOST}"
      CLIENT_URLS: "${CLIENT_URLS}"
      DEBUGGING: "${DEBUGGING}"
  runtrains-client:
    image: runtrains-client
    environment:
      REACT_APP_SERVER_HOST: "${REACT_APP_SERVER_HOST}"
      REACT_APP_SERVER_PORT: "${REACT_APP_SERVER_PORT}"
      REACT_APP_SERVER_SSL: "${REACT_APP_SERVER_SSL}"
    build:
      context: .
      args:
        - "REACT_APP_SERVER_HOST=${REACT_APP_SERVER_HOST}"
        - "REACT_APP_SERVER_PORT=${REACT_APP_SERVER_PORT}"
        - "REACT_APP_SERVER_SSL=${REACT_APP_SERVER_SSL}"
